### ISSUE TITLE
Exception when provided value for input[type=number] is an integer

### ISSUE THREAD

**Issue by akaufmann** [dart-lang/angular_components#115]
When you provide a value from type `integer` to ngModel a `NoSuchMethodError` exception is raised.
```dart
@Component(
  selector: 'foo',
  template: '''
    <material-input
      type="number"
      [(ngModel)]="amount">
    </material-input>
  ''',
  directives: const [COMMON_DIRECTIVES],
)
class FooComponent {
  int amount = 1;
}
```
```
NoSuchMethodError: method not found: 'get$length' (J.getInterceptor$asx(...).get$length is not a function)
STACKTRACE: 
TypeError: J.getInterceptor$asx(...).get$length is not a function
    at Object.J.get$length$asx (http://localhost:8080/main.dart.js:90984:43)
    at MaterialInputComponent.set$inputText (http://localhost:8080/main.dart.js:36570:18)
    at MaterialInputDefaultValueAccessor.dart.BaseMaterialInputValueAccessor.writeValue$1 (http://localhost:8080/main.dart.js:38069:20)
    at Object.setUpControl (http://localhost:8080/main.dart.js:22773:25)
    at ViewFoo0.detectChangesInternal$0 (http://localhost:8080/main.dart.js:78536:13)
    at ViewFoo0.detectCrash$0 (http://localhost:8080/main.dart.js:26561:16)
    at ViewFoo0.dart.AppView.detectChanges$0 (http://localhost:8080/main.dart.js:26549:16)
    at ViewApp1.detectChangesInternal$0 (http://localhost:8080/main.dart.js:67013:12)
    at ViewApp1.detectCrash$0 (http://localhost:8080/main.dart.js:26561:16)
    at ViewApp1.dart.AppView.detectChanges$0 (http://localhost:8080/main.dart.js:26549:16)
ORIGINAL EXCEPTION: NoSuchMethodError: method not found: 'get$length' (J.getInterceptor$asx(...).get$length is not a function)

(anonymous)	@	html_dart2js.dart:3558
dart.BrowserExceptionHandler.call$3	@	main.dart.js:28630
_runTickGuarded$0	@	application_ref.dart:472
tick$0	@	application_ref.dart:427
dart.ApplicationRefImpl__closure.call$0	@	application_ref.dart:278
dart._rootRun.func	@	zone.dart:1120
run$2	@	zone.dart:675
dart.NgZone._run$4	@	ng_zone.dart:175
(anonymous)	@	VM5952:2
run$1	@	zone.dart:1001
runGuarded$1	@	zone.dart:901
runGuarded$1	@	ng_zone.dart:310
dart.ApplicationRefImpl_closure2.call$1	@	application_ref.dart:277
runUnaryGuarded$2	@	zone.dart:1307
_sendData$1	@	stream_impl.dart:330
dart._BufferingStreamSubscription._async$_add$1	@	stream_impl.dart:257
_sendData$1	@	broadcast_stream_controller.dart:379
_checkStable$0	@	broadcast_stream_controller.dart:254
dart.NgZone._run$4	@	ng_zone.dart:213
(anonymous)	@	VM5952:2
run$1	@	zone.dart:1001
runGuarded$1	@	zone.dart:901
runGuarded$1	@	ng_zone.dart:310
call$1	@	app_view.dart:566
dart.DebugAppView_eventHandler1_closure.call$1	@	debug_app_view.dart:154
call$0	@	js_helper.dart:2456
eval$1	@	isolate_helper.dart:474
_callInIsolate	@	isolate_helper.dart:59
dart.invokeClosure	@	js_helper.dart:2456
(anonymous)	@	js_helper.dart:2476
```

**Comment by TedSander** [comment]
It isn't using the right Accessor. Needs to include this list in the directives:
https://github.com/dart-lang/angular_components/blob/master/lib/src/components/material_input/material_number_accessor.dart#L21

Specifically: MaterialNumberValueAccessor

@nshahan It looks like those aren't in the general list of directives. Should they be added?

**Comment by akaufmann** [comment]
Sorry, I forgot to add the accessor that we use in our real component. We use `materialDirectives` list.

**Comment by nshahan** [comment]
Did that resolve the issue? Is it OK to close this?

**Comment by akaufmann** [comment]
Yes, it resolve the issue.
