### ISSUE TITLE
No provider for ManagedZone! with material-button

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_components#14]
I added a button to my application
```dart
<material-button raised #dialog.show()>Show Dialog</material-button>
```
Now I get
```
Observatory listening at http://127.0.0.1:46411/
>EXCEPTION: Error in asset:angular2_components/lib/src/components/material_button/material_button.html:10:0
  EXCEPTION: Error in asset:angular2_components/lib/src/components/material_button/material_button.html:10:0
  ORIGINAL EXCEPTION: No provider for ManagedZone!
  ORIGINAL STACKTRACE:
  #0      _NullInjector.get (package:angular2/src/core/di/injector.dart:11:7)
#1      MapInjector.get (package:angular2/src/core/di/map_injector.dart:28:25)
#2      ReflectiveInjectorImpl._getByKeyDefault (package:angular2/src/core/di/reflective_injector.dart:804:18)
#3      ReflectiveInjectorImpl._getByKey (package:angular2/src/core/di/reflective_injector.dart:770:14)
#4      ReflectiveInjectorImpl.get (package:angular2/src/core/di/reflective_injector.dart:528:17)
#5      ElementInjector.get (package:angular2/src/core/linker/element_injector.dart:17:37)
#6      ElementInjector.get (package:angular2/src/core/linker/element_injector.dart:17:37)
#7      ViewMaterialButtonComponent0.createInternal (package:angular2_components/src/components/material_button/material_button.template.dart:99:166)
#8      AppView.createComp (package:angular2/src/core/linker/app_view.dart:159:12)
#9      DebugAppView.createComp (package:angular2/src/debug/debug_app_view.dart:63:30)
```

**Comment by BrownRiceRice** [comment]
I believe that you need to add the following lines to your app component: 
`directives: const [materialDirectives],
    providers: materialProviders`

That should add the provider for the ManagedZone that the button needs.

**Comment by nshahan** [comment]
You are right the comment documenting usage should show the entire component, not just the template. Thanks!

**Comment by nshahan** [comment]
This shouldn't be an issue anymore.
