### ISSUE TITLE
Error with MaterialTabPanelComponent

### ISSUE THREAD

**Issue by a14n** [dart-lang/angular_components#189]
After adding MaterialTabPanelComponent in my app I see the folloing error:

```
EXCEPTION: NullError: method not found: 'get$onTurnDone' on null
STACKTRACE: 
TypeError: Cannot read property 'get$onTurnDone' of null
    at FocusListDirective.set$listItems (http://localhost:8081/main.dart.js:29597:32)
    at ViewFixedMaterialTabStripComponent0.detectChangesInternal$0 (http://localhost:8081/main.dart.js:46662:51)
    at ViewFixedMaterialTabStripComponent0.dart.AppView.detectChanges$0 (http://localhost:8081/main.dart.js:25777:16)
    at ViewMaterialTabPanelComponent0.detectChangesInternal$0 (http://localhost:8081/main.dart.js:47314:12)
    at ViewMaterialTabPanelComponent0.dart.AppView.detectChanges$0 (http://localhost:8081/main.dart.js:25777:16)
```

To make it works I need to add the `popupBindings` provider to one of the parent component in the tree.

Is `popupBindings` really needed ? If yes I think a note should be added in the component doc.

**Comment by TedSander** [comment]
What version of angular_components are you using?

In a very recent version I removed the need for ManagedZone in focus_list and switched it to use ngZone instead. Which removes the need for 'extra' providers for this directive.

I'll slowly be removing the need for bindings, or have better defaults, but there still might be more lurking. While we transition.

**Comment by a14n** [comment]
I use angular_components-0.8.0

**Comment by TedSander** [comment]
Looking at the history change was added to 0.9.0-alpha
