### ISSUE TITLE
`componentRenderer` doesn't accept a function reference, only a field/getter with a reference to a function.

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_components#90]
```dart
  Type componentRenderer<PropertyDropdownMenuItemComponent>(dynamic _) =>
      PropertyDropdownMenuItemComponent;
```
```html
<material-dropdown-select
    [buttonText]="displayValueString ?? label"
    [selection]="selectionModel"
    [options]="options"
    [componentRenderer]="componentRenderer"
    [disabled]="readonly">
</material-dropdown-select>
```

causes
```
EXCEPTION: Cannot find reflection information on dynamic
STACKTRACE: 
#0      NoReflectionCapabilities.annotations (package:angular2/src/core/reflection/reflection.dart:35:37)
#1      Reflector.annotations (package:angular2/src/core/reflection/reflector.dart:103:37)
#2      ReflectorComponentResolver.resolveComponent (package:angular2/src/core/linker/component_resolver.dart:20:31)
#3      DynamicComponentLoaderImpl.loadNextToLocation (package:angular2/src/core/linker/dynamic_component_loader.dart:138:22)
#4      DynamicComponent._initialize (package:angular_components/src/components/dynamic_component/dynamic_component.dart:91:10)
#5      DynamicComponent.componentType= (package:angular_components/src/components/dynamic_component/dynamic_component.dart:82:7)
#6      ViewMaterialSelectDropdownItemComponent5.detectChangesInternal (package:angular_components/src/components/material_select/material_select_dropdown_item.template
...
```

changing the code to

```dart
ComponentRenderer get componentRenderer =>
      (dynamic _) => PropertyDropdownMenuItemComponent;
```
fixes the issue, but I think the first example should be valid as well.

**Comment by nshahan** [comment]
To clarify, Where did you make this change?

**Comment by zoechi** [comment]
It's in the host component where the dropdown is used as a child.

**Comment by nshahan** [comment]
If this turns up in the current versions again we can take another look.
